/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as InstructionsRouteImport } from './routes/instructions'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionsRoute = InstructionsRouteImport.update({
  id: '/instructions',
  path: '/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/camera': typeof CameraRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/fleet': typeof FleetRoute
  '/instructions': typeof InstructionsRoute
  '/learning': typeof LearningRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/camera': typeof CameraRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/fleet': typeof FleetRoute
  '/instructions': typeof InstructionsRoute
  '/learning': typeof LearningRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/tools': typeof ToolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/camera': typeof CameraRoute
  '/commands': typeof CommandsRoute
  '/events': typeof EventsRoute
  '/fleet': typeof FleetRoute
  '/instructions': typeof InstructionsRoute
  '/learning': typeof LearningRoute
  '/missions': typeof MissionsRoute
  '/settings': typeof SettingsRoute
  '/simulation': typeof SimulationRoute
  '/tools': typeof ToolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/camera'
    | '/commands'
    | '/events'
    | '/fleet'
    | '/instructions'
    | '/learning'
    | '/missions'
    | '/settings'
    | '/simulation'
    | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/camera'
    | '/commands'
    | '/events'
    | '/fleet'
    | '/instructions'
    | '/learning'
    | '/missions'
    | '/settings'
    | '/simulation'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/camera'
    | '/commands'
    | '/events'
    | '/fleet'
    | '/instructions'
    | '/learning'
    | '/missions'
    | '/settings'
    | '/simulation'
    | '/tools'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CameraRoute: typeof CameraRoute
  CommandsRoute: typeof CommandsRoute
  EventsRoute: typeof EventsRoute
  FleetRoute: typeof FleetRoute
  InstructionsRoute: typeof InstructionsRoute
  LearningRoute: typeof LearningRoute
  MissionsRoute: typeof MissionsRoute
  SettingsRoute: typeof SettingsRoute
  SimulationRoute: typeof SimulationRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructions': {
      id: '/instructions'
      path: '/instructions'
      fullPath: '/instructions'
      preLoaderRoute: typeof InstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CameraRoute: CameraRoute,
  CommandsRoute: CommandsRoute,
  EventsRoute: EventsRoute,
  FleetRoute: FleetRoute,
  InstructionsRoute: InstructionsRoute,
  LearningRoute: LearningRoute,
  MissionsRoute: MissionsRoute,
  SettingsRoute: SettingsRoute,
  SimulationRoute: SimulationRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
